(debuglog "Hello, World, here is an atom:" :iamanatom)
(defun myfun (var) (debuglog var)) 
(myfun :myfunworks)
((lambda (a) (debuglog a)) :atom)
(debuglog a)
(defun testlog (a ...) (seq
    (debuglog "a" a)
    (debuglog "..." ...)))
(testlog :test :work :whatever)
(def helloworld (pure "hello world"))
(debuglog helloworld (helloworld))
(debuglog "+" (+ 1.2 15))
(debuglog "-" (- 1 3))
(debuglog "*" (* 10 10))
(debuglog "/" (/ 1 3 2))
