(debuglog "Hello, World, here is an atom:" :iamanatom)
(defun myfun (var) (debuglog var)) 
(myfun :myfunworks)
((lambda (a) (debuglog a)) :atom)
(debuglog a)
(def helloworld (pure "hello world"))
(debuglog helloworld (helloworld))
(debuglog + (+ 1.2 15))
