name: Build
on:
  - push
  - pull_request

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout repository
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 8
      - name: Set up gradle cache
        uses: gradle/gradle-build-action@v2
      - name: Build with gradle
        run: ./gradlew clean build --stacktrace
      - name: Test with gradle
        run: ./gradlew test testLisps --stacktrace
      - name: Generate markdown test report
        if: ${{ !cancelled() }}
        run: |
          curl -L https://github.com/kitproj/junit2md/releases/download/v0.1.0/junit2md_0.1.0_Linux_x86_64.tar.gz | tar -zxvf - junit2md
          chmod +x junit2md
          ./junit2md < build/test-results/nealisp/results.xml > "$GITHUB_STEP_SUMMARY"